[package]
name = "jrsonnet-parser"
description = "jsonnet language parser and AST"
version.workspace = true
repository.workspace = true
authors = ["Yaroslav Bolyukin <iam@lach.pw>"]
license = "MIT"
edition = "2021"

[features]
default = []
exp-destruct = []
exp-null-coaelse = []
# Implement serialization of AST using structdump
#
# Structdump generates code, which exactly replicated passed AST
# Contrary to serde, has no code bloat problem, and is recommended
#
# The only limitation is serialized form is only useable if built from build script
structdump = ["dep:structdump", "jrsonnet-interner/structdump"]
# Implement serialization of AST using serde
#
# Warning: as serde doesn't deduplicate strings, `Source` struct will bloat
# output binary with repeating source code. To resolve this issue, you should either
# override serialization of this struct using custom `Serializer`/`Deserializer`,
# not rely on Source, and fill its `source_code` with empty value, or use `structdump`
# instead
serde = ["dep:serde"]

[dependencies]
jrsonnet-interner.workspace = true
jrsonnet-gcmodule.workspace = true

static_assertions.workspace = true

peg.workspace = true

serde = { workspace = true, features = ["derive", "rc"], optional = true }
structdump = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
pretty_assertions = { version = "1.4.0" }
test-case = "3.3.1"
